// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqeqfpdrkwblmuwtaxvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZXFmcGRya3dibG11d3RheHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzUxNjAsImV4cCI6MjA2MzY1MTE2MH0.aP4GXZCP7X76qMwIJSaCUWlT_oRJ9c2fg3fF3QwKyPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);